// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package envelope

import "time"

type Authority struct {
	// The authority-bearing seat, or null (the common case).
	Seat interface{} `json:"seat,omitempty" yaml:"seat,omitempty" mapstructure:"seat,omitempty"`

	// Relayed authority is provably weaker than direct (finding-151). none carries no
	// authority.
	Strength Strength `json:"strength" yaml:"strength" mapstructure:"strength"`
}

type Content struct {
	// The payload for this content type. Bounded; use refs for anything large.
	Data interface{} `json:"data,omitempty" yaml:"data,omitempty" mapstructure:"data,omitempty"`

	// Pointers, not payload: bd:, finding:, file:, url:, pr:.
	Refs []string `json:"refs,omitempty" yaml:"refs,omitempty" mapstructure:"refs,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type Type `json:"type" yaml:"type" mapstructure:"type"`
}

// Intentional agent speech carried over the bus, peer to peer including the human.
// This is an A2A v1.0 compatible profile: the fields here map onto A2A v1.0
// message semantics (the FIPA-ACL performative subset maps to A2A message intent),
// and codegen emits Go and Rust types plus validators from this one schema so the
// bound consumers cannot drift. Bound consumers: marvel (Go) and beadle (Rust).
// See contracts/README.md for the A2A mapping and the codegen targets. Time and
// UUID fields carry both a format annotation and an always-enforced pattern, so
// validation does not depend on the validator running in format-assertion mode.
type DirectorEnvelopeSchemaJson struct {
	// Authority corresponds to the JSON schema field "authority".
	Authority Authority `json:"authority" yaml:"authority" mapstructure:"authority"`

	// Content corresponds to the JSON schema field "content".
	Content Content `json:"content" yaml:"content" mapstructure:"content"`

	// Reply chain. On the first message of a chain it equals message_id.
	ConversationID *string `json:"conversation_id,omitempty" yaml:"conversation_id,omitempty" mapstructure:"conversation_id,omitempty"`

	// Work-item thread across many messages. The loop guard keys on it
	// (correlation_id plus performative plus recipient within a cool-down).
	CorrelationID *string `json:"correlation_id,omitempty" yaml:"correlation_id,omitempty" mapstructure:"correlation_id,omitempty"`

	// Optional RFC3339 queue TTL; a stale control message dies rather than acting
	// late.
	ExpiresAt *time.Time `json:"expires_at,omitempty" yaml:"expires_at,omitempty" mapstructure:"expires_at,omitempty"`

	// Optional. The message_id this answers.
	InReplyTo *string `json:"in_reply_to,omitempty" yaml:"in_reply_to,omitempty" mapstructure:"in_reply_to,omitempty"`

	// ULID: sortable, unique. Consumers dedupe on this (delivery is at least once).
	MessageID string `json:"message_id" yaml:"message_id" mapstructure:"message_id"`

	// Performative corresponds to the JSON schema field "performative".
	Performative Performative `json:"performative" yaml:"performative" mapstructure:"performative"`

	// Recipient corresponds to the JSON schema field "recipient".
	Recipient Recipient `json:"recipient" yaml:"recipient" mapstructure:"recipient"`

	// Optional RFC3339 expectation; drives escalation.
	ReplyBy *time.Time `json:"reply_by,omitempty" yaml:"reply_by,omitempty" mapstructure:"reply_by,omitempty"`

	// Envelope schema version. Integer per the session-029 rule.
	SchemaVersion int `json:"schema_version" yaml:"schema_version" mapstructure:"schema_version"`

	// Sender corresponds to the JSON schema field "sender".
	Sender Sender `json:"sender" yaml:"sender" mapstructure:"sender"`

	// SentAt corresponds to the JSON schema field "sent_at".
	SentAt time.Time `json:"sent_at" yaml:"sent_at" mapstructure:"sent_at"`

	// Trace corresponds to the JSON schema field "trace".
	Trace *Trace `json:"trace,omitempty" yaml:"trace,omitempty" mapstructure:"trace,omitempty"`
}

type Performative string

const (
	PerformativeACCEPTPROPOSAL Performative = "ACCEPT-PROPOSAL"
	PerformativeAGREE          Performative = "AGREE"
	PerformativeCANCEL         Performative = "CANCEL"
	PerformativeCFP            Performative = "CFP"
	PerformativeFAILURE        Performative = "FAILURE"
	PerformativeINFORM         Performative = "INFORM"
	PerformativeNOTUNDERSTOOD  Performative = "NOT-UNDERSTOOD"
	PerformativePROPOSE        Performative = "PROPOSE"
	PerformativeQUERY          Performative = "QUERY"
	PerformativeREFUSE         Performative = "REFUSE"
	PerformativeREJECTPROPOSAL Performative = "REJECT-PROPOSAL"
	PerformativeREQUEST        Performative = "REQUEST"
)

type Recipient struct {
	// Where the message goes. role:// resolves to the current holder at delivery; an
	// unresolvable address returns NOT-UNDERSTOOD to the sender.
	Address string `json:"address" yaml:"address" mapstructure:"address"`

	// Team corresponds to the JSON schema field "team".
	Team *string `json:"team,omitempty" yaml:"team,omitempty" mapstructure:"team,omitempty"`
}

type Sender struct {
	// The roster address, stable across restarts. Closed character class (R-76): no
	// dot, star, angle bracket, or space, because it is interpolated into a NATS
	// subject (director#3).
	AgentID string `json:"agent_id" yaml:"agent_id" mapstructure:"agent_id"`

	// Principal corresponds to the JSON schema field "principal".
	Principal interface{} `json:"principal,omitempty" yaml:"principal,omitempty" mapstructure:"principal,omitempty"`

	// Current role. Informational only, never a routing or authorization input (R-71,
	// R-82).
	Role *string `json:"role,omitempty" yaml:"role,omitempty" mapstructure:"role,omitempty"`

	// The current harness session UUID, the key (R-71). Nullable now; required once
	// marvel sets it at spawn (R-73, R-84). Nothing derives from it yet. The pattern
	// applies only when the value is a string, so null still validates.
	Session *string `json:"session,omitempty" yaml:"session,omitempty" mapstructure:"session,omitempty"`

	// Workspace corresponds to the JSON schema field "workspace".
	Workspace string `json:"workspace" yaml:"workspace" mapstructure:"workspace"`
}

type Strength string

const (
	StrengthDirect  Strength = "direct"
	StrengthNone    Strength = "none"
	StrengthRelayed Strength = "relayed"
)

type Trace struct {
	// OtelTraceparent corresponds to the JSON schema field "otel_traceparent".
	OtelTraceparent *string `json:"otel_traceparent,omitempty" yaml:"otel_traceparent,omitempty" mapstructure:"otel_traceparent,omitempty"`
}

type Type string

const (
	TypePointer Type = "pointer"
	TypeResult  Type = "result"
	TypeSignal  Type = "signal"
	TypeTask    Type = "task"
	TypeText    Type = "text"
)
